// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR50YsFWGyiR7dKcI7gZ6QE2UNJJ6hF98',
    appId: '1:253104354974:android:555a47e166273d93916d8f',
    messagingSenderId: '253104354974',
    projectId: 'prontosindico-59bd4',
    databaseURL: 'https://prontosindico-59bd4-default-rtdb.firebaseio.com',
    storageBucket: 'prontosindico-59bd4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkGMkpZXgNqTtrbdtgBm78h0jwEwG10XI',
    appId: '1:253104354974:ios:a06d41ea3e5a146f916d8f',
    messagingSenderId: '253104354974',
    projectId: 'prontosindico-59bd4',
    databaseURL: 'https://prontosindico-59bd4-default-rtdb.firebaseio.com',
    storageBucket: 'prontosindico-59bd4.firebasestorage.app',
    iosClientId: '253104354974-8i3flvgeqqvia5jj7vnshm2gsvcvp8fj.apps.googleusercontent.com',
    iosBundleId: 'com.prontosindico.prontosindico',
  );
}
